spring.application.name=registration_Management_System

spring.datasource.url=jdbc:postgresql://localhost:5432/{DB_name}
spring.datasource.username=postgres
spring.datasource.password={DB_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
